var en = {
    Save: "Uložit",
    "Save all": "Uložit vše",
    Rename: "Přejmenovat",
    Open: "Otevřít",
    Edit: "Upravit",
    Delete: "Smazat",
    Folder: "Složka",
    "Add New": "Přidat",
    Size: "Velikost",
    Date: "Datum",
    "back to parent folder": "zpět",
    Download: "Stáhnout",
    Type: "Typ",
    Information: "Informace",
    Files: "Soubory",
    Table: "Tabulka",
    Cards: "Karty",
    Total: "Celkem",
    "Are you sure ?": "Jste si jistí ?",
    Details: "Detaily",
    "Enter a new name": "Zadejte nový název",
    Add: "Přidat",
    "Select something": "Vyberte něco",
    "Download file": "Stáhnout soubor",
    Preview: "Náhled",
    Refresh: "Obnovit",
    "Are you sure you want to exit without saving?": "Opravdu chcete odejít bez uložení?",
    "Save before closing?": "Uložit před zavřením?",
    Copy: "Kopírovat",
    Cut: "Vyjmout",
    Paste: "Vložit",
    "Deleting...": "Mazání...",
    "Copying...": "Kopírování...",
    "Moving...": "Přesouvání...",
    Folders: "Složky",
    "Search results": "Výsledky hledání",
    "Search results in": "Výsledky hledání v",
    "Search files and folders": "Hledat soubory a složky",
    "Add new file": "Vytvořit soubor",
    "Add new folder": "Vytvořit složku",
    "Upload file": "Nahrát soubor",
    folder: "složka",
    file: "soubor",
    archive: "archiv",
    audio: "audio",
    image: "obrázek",
    video: "video",
    code: "kód",
    document: "dokument",
    of: "z",
    used: "využito",
    "Open item location": "Otevřít umístění položky",
    "Are you sure you want to delete": "Opravdu chcete smazat",
    "these items:": "tyto položky:",
    "this item:": "tuto položku:",
    "Delete files": "Smazat soubory",
    and: "a",
    "more file(s)": "další soubor(y)",
    "Close the editor": "Zavřít editor",
    "Close this file": "Zavřít tento soubor",
    "Owner": "Vlastník",
    "Permissions": "Oprávnění",
    "Change Permissions": "Změnit oprávnění",
    "Set": "Nastavit",
    "Extract": "Rozbalit archiv",
    "Extract directory": "Rozbalit složku",
    "Extracting...": "Rozbalování...",
    "Compress": "Archivovat",
    "Compressing...": "Archivování...",
};